[02/Dec/2014 15:13:07] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 112, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 369, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 241, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 248, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/sander/Downloads/django-trunk/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 107, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 348
    print "alles goed?"
        ^
SyntaxError: invalid syntax
[02/Dec/2014 15:13:08] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 112, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 369, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 241, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 248, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/sander/Downloads/django-trunk/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 107, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 348
    print "alles goed?"
        ^
SyntaxError: invalid syntax
[02/Dec/2014 15:13:08] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 112, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 369, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 241, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 248, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/sander/Downloads/django-trunk/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 107, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 348
    print "alles goed?"
        ^
SyntaxError: invalid syntax
[02/Dec/2014 15:13:57] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 112, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 369, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 241, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 248, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/sander/Downloads/django-trunk/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 107, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 347
    print objectlijst_filtered
        ^
SyntaxError: invalid syntax
[02/Dec/2014 15:13:58] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 112, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 369, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 241, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 248, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/sander/Downloads/django-trunk/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sander/Downloads/django-trunk/django/core/urlresolvers.py", line 107, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 347
    print objectlijst_filtered
        ^
SyntaxError: invalid syntax
[02/Dec/2014 15:15:18] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 347, in stock
    objectlijst_filtered = list(chain(objects, objectlijst_filtered))
UnboundLocalError: local variable 'objectlijst_filtered' referenced before assignment
[02/Dec/2014 15:15:31] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 348, in stock
    objectlijst_filtered = list(chain(objects, objectlijst_filtered))
TypeError: 'NoneType' object is not iterable
[02/Dec/2014 15:15:35] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 348, in stock
    objectlijst_filtered = list(chain(objects, objectlijst_filtered))
TypeError: 'NoneType' object is not iterable
[02/Dec/2014 15:17:51] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 343, in stock
    for key, d in direct_leverbaar.items():
AttributeError: 'list' object has no attribute 'items'
[02/Dec/2014 15:18:20] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 343, in stock
    for key, d in direct_leverbaar.items():
AttributeError: 'list' object has no attribute 'items'
[02/Dec/2014 15:18:40] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 343, in stock
    for key, d in direct_leverbaar.items():
AttributeError: 'list' object has no attribute 'items'
[02/Dec/2014 15:18:51] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 343, in stock
    for key, d in direct_leverbaar.items():
AttributeError: 'list' object has no attribute 'items'
[02/Dec/2014 15:19:22] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 343, in stock
    for key, d in direct_leverbaar.items():
AttributeError: 'list' object has no attribute 'items'
[02/Dec/2014 15:20:45] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 343, in stock
    for (key, d) in direct_leverbaar.items():
AttributeError: 'list' object has no attribute 'items'
[02/Dec/2014 15:21:18] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 353, in stock
    objectlijst_filtered = list(chain(objects, objectlijst_filtered))
UnboundLocalError: local variable 'objectlijst_filtered' referenced before assignment
[02/Dec/2014 15:21:25] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 353, in stock
    objectlijst_filtered = list(chain(objects, objectlijst_filtered))
UnboundLocalError: local variable 'objectlijst_filtered' referenced before assignment
[02/Dec/2014 15:21:43] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 344, in stock
    print key + " : " + d
TypeError: unsupported operand type(s) for +: 'int' and 'str'
[02/Dec/2014 15:21:58] ERROR [django.request:240] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/home/sander/Downloads/django-trunk/django/core/handlers/base.py", line 125, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 130, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 326, in filters
    objectlijst = stock(objectlijst,levering)
  File "/home/sander/grive/School/Kwartaal 1/Project local/A-Pc/Website/pcbuilder/views.py", line 352, in stock
    objectlijst_filtered = list(chain(objects, objectlijst_filtered))
UnboundLocalError: local variable 'objectlijst_filtered' referenced before assignment
