[30/Nov/2014 13:03:24] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam.replace(',','.')) < float(minPriceSliderValue.replace(',','')):
AttributeError: 'int' object has no attribute 'replace'
[30/Nov/2014 13:03:24] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam.replace(',','.')) < float(minPriceSliderValue.replace(',','')):
AttributeError: 'int' object has no attribute 'replace'
[30/Nov/2014 13:03:24] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam.replace(',','.')) < float(minPriceSliderValue.replace(',','')):
AttributeError: 'int' object has no attribute 'replace'
[30/Nov/2014 13:03:50] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam.replace(',','.')) < float(minPriceSliderValue.replace(',','.')):
AttributeError: 'int' object has no attribute 'replace'
[30/Nov/2014 13:03:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam.replace(',','.')) < float(minPriceSliderValue.replace(',','.')):
AttributeError: 'int' object has no attribute 'replace'
[30/Nov/2014 17:52:24] WARNING [django.request:143] Not Found: /favicon.ico
[30/Nov/2014 17:52:31] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 17:52:37] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 17:52:48] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 17:53:27] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 17:53:42] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 17:57:05] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 17:57:09] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 18:01:06] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[30/Nov/2014 18:01:16] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 117, in detail
    return render_to_response('detail.html', {'Componenten': (categorieObject.objects,), 'Categorie' : categorie.lower(), 'Product': product, 'Prijs': prijs, 'Productid': productid},
UnboundLocalError: local variable 'categorieObject' referenced before assignment
[01/Dec/2014 12:50:03] WARNING [django.request:143] Not Found: /favicon.ico
