[16/Oct/2014 16:06:33] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 31
    return render_to_response('processoren.html', {'Processoren': processoren, start, end, sl},
                                                                                    ^
SyntaxError: invalid syntax
[16/Oct/2014 16:08:28] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 91
    return render_to_response('moederbord.html', {'Processoren': processoren, start, end, sl},
                                                                                   ^
SyntaxError: invalid syntax
[16/Oct/2014 16:11:34] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 13, in <module>
    sl = (start) % ":%d" % (end)
TypeError: unsupported operand type(s) for %: 'int' and 'str'
[16/Oct/2014 16:27:24] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 89, in moederborden
    start, end = limits(request)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 123, in limits
    app, pagina = pages(request)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 116, in pages
    aantal = request.GET.get('aantal', app)
NameError: global name 'app' is not defined
[16/Oct/2014 17:06:44] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 90, in moederborden
    start, end = limits(request)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 124, in limits
    app, pagina = pages(request)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 120, in pages
    pagina = int(pagina) - 1
ValueError: invalid literal for int() with base 10: '2/'
[16/Oct/2014 17:39:48] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
[16/Oct/2014 17:59:52] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
[16/Oct/2014 17:59:59] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
[16/Oct/2014 18:00:07] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
[16/Oct/2014 18:00:53] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
[16/Oct/2014 18:01:05] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
[16/Oct/2014 18:01:38] ERROR [django.request:231] Internal Server Error: /moederborden/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 92, in moederborden
    processoren = Processoren.objects(categorie__contains='Moederborden')[start:end]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 139, in __getitem__
    raise err
IndexError: Cursor instances do not supportnegative indices
